### ISSUE TITLE
Crash handling

### ISSUE THREAD

**Issue by jchristn** [agrinman/tunnelto#13]
Improve the user experience by automatically sending crash reports (rather than requesting the user do it) and restarting the tunnel.  I don't have a way to see that a tunnel is down unless I look at my console window, and finding the crash report is tedious.  Cheers

**Comment by agrinman** [comment]
Noted thanks. It's not entirely clear how to do this in a privacy preserving way. Maybe a command `tunnelto send-crash-reports` or something...

**Comment by agrinman** [comment]
Btw looking into your crash reports -- these should never be happening in the first place so something is wrong...

**Comment by jchristn** [comment]
What other information can I provide to help debug?

**Comment by jchristn** [comment]
Dunno what you did but it's been steady forever now.  Thanks!
