### ISSUE TITLE
queryParams are Ignored

### ISSUE THREAD

**Issue by dhakchianandan** [agrinman/tunnelto#15]
Query Params are being ignored while forwarding the request to local server. 
I tried ngrok to see if any issue with the request. The request works fine with ngrok.

Tunneling was working for the same few weeks back.

Sample Req Details

`Request Received In Terminal`
`200		POST	/api/v1/me/phone/calldetails?location_id=&location_name=&client_id=&client_name=`

`tunnelto inspector`
`14:30:21	2s	200	POST	/api/v1/me/phone/calldetails	0 KB	0 KB`
`Text`
`AccountSid=&ApiVersion=2010-04-01&ApplicationSid=&CallSid=&CallStatus=completed&Called=&Caller=&DialCallSid=&DialCallStatus=&Direction=&From=&To=`

Verified With 0.1.9
  url "https://github.com/agrinman/tunnelto/archive/0.1.9.zip"
  sha256 "8bba2bf602365148e777cd82d23a75fac0d4d96db3d2006cb01b0a275dc9372f"
 
The Request works fine

**Comment by agrinman** [comment]
What version are you on? Latest is tunnelto 0.1.11

**Comment by agrinman** [comment]
Never mind -- can confirm this is a regression in the last update. Will push a fix very soon, thanks for the find!

**Comment by agrinman** [comment]
This should now be fixed as of version 0.1.12 -- please let me know if you are still having issues!

**Comment by dhakchianandan** [comment]
This is fixed now.
