### ISSUE TITLE
Couldn't execute tunnelto file on Ubuntu server 16 (i386)

### ISSUE THREAD

**Issue by anhtuank7c** [agrinman/tunnelto#16]
I had download `tunnelto-linux.tar.gz` to my server then using `tar -xvf tunnelto-linux.tar.gz` to extract.

I got this issue when trying to execute tunnelto

`./tunnelto: cannot execute binary file: Exec format error`

**Comment by agrinman** [comment]
I recommend installing from source (install rust with https://rustup.rs and then run the cargo install command as in the README)-- the binary in the releases page is only 64 bit which is not with your 32 bit system.

**Comment by anhtuank7c** [comment]
I still couldn't install via cargo `cargo 1.43.0`

![Screen Shot 2020-08-02 at 14 18 19](https://user-images.githubusercontent.com/3163410/89117831-2d332e80-d4cb-11ea-94e7-d6c64fc36259.png)

**Comment by agrinman** [comment]
It looks like curl is not built with http2 — can you try reinstalling curl or see if there’s a way to install it with http2 support? This is an issue with simply downloading a dependencies for cargo (not even at the installation step).

**Comment by Arun-N** [comment]
Hi! I'm facing the same issue, but with a 64-bit system. I'm trying to use it on a Raspberry Pi 4 running Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-1026-raspi2 aarch64)

I used ```curl -LJO https://github.com/agrinman/tunnelto/releases/download/0.1.12/tunnelto-linux.tar.gz``` to download it and ```tar -xzf tunnelto-linux.tar.gz``` to extract it. Trying to run it, I get this error ```zsh: exec format error: ./tunnelto```

**Comment by anhtuank7c** [comment]
@agrinman I follow the instruction to install rust then cargo install with no luck (Ubuntu 20.04 LTS 64 bit ARM)

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source $HOME/.cargo/env
cargo install tunnelto
```

![image](https://user-images.githubusercontent.com/3163410/97251795-25212b80-183b-11eb-9d71-99b0db4661be.png)

**Comment by anhtuank7c** [comment]
> I recommend installing from source (install rust with https://rustup.rs and then run the cargo install command as in the README)-- the binary in the releases page is only 64 bit which is not with your 32 bit system.

It works. Thank you so much.
