### ISSUE TITLE
Incorrect text in help menu

### ISSUE THREAD

**Issue by jchristn** [agrinman/tunnelto#22]
Using multiple ```v``` on the command prompt is not allowed, though the help menu indicates that it is.
```
D:\>tunnelto --port xxxx --subdomain yyyy -vv
error: The argument '--verbose' was provided more than once, but cannot be used multiple times

USAGE:
    tunnelto --port <port> --subdomain <sub-domain> --verbose

For more information try --help

D:\>tunnelto --help
tunnelto 0.1.9
Alex Grinman <alex@tunnelto.dev>
Expose your local web server to the internet with a public url.

USAGE:
    tunnelto [FLAGS] [OPTIONS] [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    -v, --verbose    A level of verbosity, and can be used multiple times   <<<<<<<<<<<<
```

**Comment by agrinman** [comment]
Whoops -- thx.

**Comment by agrinman** [comment]
Btw -- we're up to 0.1.12 of the tunnelto cli now :)

**Comment by jchristn** [comment]
Ok - I'll give the latest a run to see if that other issue is resolved.  Thx!

**Comment by jchristn** [comment]
![image](https://user-images.githubusercontent.com/1421081/92428869-29876d00-f145-11ea-84c4-b1ed723c1f35.png)

**Comment by jchristn** [comment]
Found it on the release page, link on website is broken, should be ```https://github.com/agrinman/tunnelto/releases/download/0.1.12/tunnelto-windows.exe```

**Comment by agrinman** [comment]
Fixed
