### ISSUE TITLE
Refresh Access key

### ISSUE THREAD

**Issue by amykapernick** [agrinman/tunnelto#23]
I accidentally added my access key to a public repo, but there's no option to refresh it.

I contacted support but have had no response and it's been a few weeks

**Comment by agrinman** [comment]
we're working on a feature to rotate your auth key -- sorry for the delay!

**Comment by agrinman** [comment]
Released!
<img width="889" alt="Screen Shot 2020-09-27 at 6 53 00 PM" src="https://user-images.githubusercontent.com/356333/94377877-c1e49200-00f2-11eb-957c-5b14d01f531f.png">
