### ISSUE TITLE
Sudden crashes when running jupyter-notebook

### ISSUE THREAD

**Issue by Omar-Elrefaei** [agrinman/tunnelto#3]
I have been getting `Error: Io(Custom { kind: Other, error: "" })` consistently.
I would be happy to supply you with a more comprehensive stack trace soon. It would be much easier though if you throw me a few steps to follow.

**Comment by agrinman** [comment]
Aw that's no good. Let's figure out what's causing it. 
Please run the CLI with the `--verbose` flag, and post the output here. 
Thanks!

**Comment by agrinman** [comment]
@Omar-Elrefaei please upgrade to version 0.1.9 for the client and give it a try again -- the issue should be addressed in the latest release. Please re-open if not the case!
