### ISSUE TITLE
Stuck/slow OPTIONS response when no body

### ISSUE THREAD

**Issue by natanavra** [agrinman/tunnelto#30]
Noticed when using Tunnelto.dev with a nodejs/express app and returning an empty response for OPTIONs request results in very long request time (20-60 seconds), it works eventually but very slow to work with and test.
Here's how I used to handle OPTIONS:
```js
if(req.method === 'OPTIONS') {
  return res.status(200).end();
}
```

Once I changed the response to have a body, tunnelto.dev started handling it much faster:
```js
if(req.method === 'OPTIONS') {
  // add some check if it's tunnelto.dev (check headers.origin or headers.referer)
  return res.send({ success: true }).end();
}
```

**Comment by agrinman** [comment]
#37
