### ISSUE TITLE
Connect to HTTPS localhost

### ISSUE THREAD

**Issue by sravanco** [agrinman/tunnelto#33]
It doesn't connect to my localhost with https://localhost:8080/.  tunneto tries only for http://localhost:8080.
Anything I should do while setup? or this is something not available yet?

**Comment by agrinman** [comment]
just added this on master: https://github.com/agrinman/tunnelto/commit/5d6f667760d7dcf1ed9e0e7488415fc2506eec19

the command can be used like `tunnelto --scheme https --port 8080"

**Comment by sravanco** [comment]
@agrinman does it take some time to get updated in Homebrew? 
I have updated tunnelto just now and _--scheme_ not yet available.

**Comment by agrinman** [comment]
Correct -- I haven't updated brew yet

**Comment by sravanco** [comment]
Any estimate when it will be available in brew?

**Comment by sravanco** [comment]
The direct mac version too is old, 0.1.9.
Any clue how can I have the latest version with your fix? It's been a pain for me to update urls to switch between http & https when working with my web server and webhooks(sender supports only https :( )
