### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by wandyirawan** [agrinman/tunnelto#38]
hi tunnelto.dev, i have try tunnnelto to access my react app at port 4200, but when i try the tunnel just show invalid host header, 

i have try 
` tunnelto -p 4200 -s mainWeb -h localhost`

or 
` tunnelto -p 4200 -s mainWeb`

but noting happens, how to fix it? thanks

**Comment by agrinman** [comment]
Can you provide some more information like the output you get running it with the verbose command `-v`?

**Comment by dcg90** [comment]
Hello @agrinman, I'm getting the same error for an angular/asp.net core app. I'm starting tunnelto like `tunnelto.exe -s dev-env -p 50815` but when I navigate to [https://dev-env.tunnelto.dev/](https://dev-env.tunnelto.dev/) I get a **bad request - invalid hostname** response. I inspected the request on the dashboard and I see the host header is set to `dev-env.tunnelto.dev` (which makes sense) but I'm wondering if there's a way to override this header to be localhost:50815? 

Thanks.

**Comment by agrinman** [comment]
Can you just set the host header on your request, this isn't a tunnelto issue as the request arrives as sent

**Comment by agrinman** [comment]
Closing this for now please, re-open if there's some weird behavior with tunnelto. Thanks!
