### ISSUE TITLE
ERROR tunnelto > got data but no stream to send it to.   what is this question,how to fix it? tks!

### ISSUE THREAD

**Issue by lidwt721** [agrinman/tunnelto#4]
![image](https://user-images.githubusercontent.com/20960402/85935836-66eea380-b927-11ea-9347-ca4363017aae.png)

**Comment by agrinman** [comment]
Are you running a local server on port 8000? If not there's no where for tunnelto to forward an incoming request.
For example, try `python -m SimpleHTTPServer` and then go to your tunnel in the browser.

**Comment by lidwt721** [comment]
tks!  As you said，i did it ，thank you very much！
![image](https://user-images.githubusercontent.com/20960402/85936356-6a385e00-b92c-11ea-8fe5-ee0c92bebb03.png)
