### ISSUE TITLE
anonymous pull of docker image doesn't work

### ISSUE THREAD

**Issue by koalp** [agrinman/tunnelto#40]
The README.md mentions [an image available on the *github package docker registry*](https://github.com/agrinman/tunnelto/packages/295195)

However, when I try to pull this image, I have an `unauthorized` error.

```
unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
Error: Error initializing source docker://docker.pkg.github.com/agrinman/tunnelto/tunnelto_server:0.1.10: Error reading manifest 0.1.10 in docker.pkg.github.com/agrinman/tunnelto/tunnelto_server: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
```

Maybe this issue is linked to [the introduction of the *github container registry*](https://github.blog/2020-09-01-introducing-github-container-registry/) that seems to replace the *github packages docker registry*.
I couldn't find information about the possibility of anonymously pull images on the *github package docker registry* (the one currently in use in this repo?)

**Comment by agrinman** [comment]
https://docs.github.com/en/packages/guides/configuring-docker-for-use-with-github-packages#about-docker-and-github-packages

**Comment by koalp** [comment]
Thank you for your answer but I read the documentation already and know that it works when you login to the *github package docker registry*.

My issue was about providing the docker image for download without having to login, as users may expect the image advertised in the readme to be available without log in.
The use case is self-hosted deployment, where you may not want to manage github tokens to login to *github package docker registry*.
