### ISSUE TITLE
Start subcommand may not exist

### ISSUE THREAD

**Issue by Kumassy** [agrinman/tunnelto#43]
Hi.
I'm interested in this awesome project!

I found a possible mistake in [README.md](https://github.com/agrinman/tunnelto/blob/master/README.md). Should this line 

```
CTRL_HOST="localhost" CTRL_PORT=5000 CTRL_TLS_OFF=1 cargo run --bin tunnelto -- start -p 8000
```

be 

```
CTRL_HOST="localhost" CTRL_PORT=5000 CTRL_TLS_OFF=1 cargo run --bin tunnelto -- -p 8000
```

?

**Comment by agrinman** [comment]
Correct this was old, thanks will fix it.
