### ISSUE TITLE
Certificate on server

### ISSUE THREAD

**Issue by hons82** [agrinman/tunnelto#46]
I've just tried to run the server locally on my machine, to have my domain for the tunnels.
What I did not find is how I could set a server certificate under which the tunnel is reachable.

**Comment by agrinman** [comment]
You need to set up a tls forward proxy to get TLS. Our hosted version does this for you, but it's not (currently) part of this open source project.

**Comment by agrinman** [comment]
Closing this for now, happy to accept a pull request on this though!
