### ISSUE TITLE
Version checker should only recommend monotonic increases maybe

### ISSUE THREAD

**Issue by xmo-odoo** [agrinman/tunnelto#47]
I just installed tunnelto for some testing. Did so via `cargo install`. As 0.1.17 has apparently been released on `Cargo` but the github release hasn't been cut yet, I get the following:

    New version available: 0.1.17 => 0.1.16 (https://github.com/agrinman/tunnelto/releases/tag/0.1.16)

That's a bit strange, even / especially if 0.1.17 only exists to fix a `cargo install` issue (which I assume is the case given the commit message), as 0.1.16 might not work at all (I've not tested so no idea).

**Comment by agrinman** [comment]
Fixed
