### ISSUE TITLE
[Feature Request] Web Inspect

### ISSUE THREAD

**Issue by trylovetom** [agrinman/tunnelto#6]
Web inspect like [ngork](https://ngrok.com/docs#inspect) will be very useful.

**Comment by amykapernick** [comment]
Seconded, in particular the replay option - <https://ngrok.com/docs#inspect-replay>. It's super useful to be able to replay when building things to replay the API request

**Comment by agrinman** [comment]
Version 0.1.10 features a new web inspector dashboard served from the command line. Features include replay and inspecting headers and body data. Please give it a try! Appreciate feedback.

**Comment by agrinman** [comment]
Closing for now as we have basic functionality for the web inspector + replay.
