### ISSUE TITLE
UnexpectedEof

### ISSUE THREAD

**Issue by mcroni** [agrinman/tunnelto#7]
Hi, been getting this error since morning when i try to spin a tunnel `Error: Tls(Custom { kind: UnexpectedEof, error: "unexpected EOF during handshake" })`

**Comment by agrinman** [comment]
What do you get if you run `curl -v https://wormhole.tunnelto.dev:10001/health_check`

**Comment by mcroni** [comment]
Hi @agrinman . I just downloaded the latest release and it working perfectly. Thanks for this tool. It's awesome
