### ISSUE TITLE
How does this compare featurewise to ngrok or localtunnel?

### ISSUE THREAD

**Issue by cktang88** [agrinman/tunnelto#9]
I was looking around for something similar to this, and it seems that these are very similar services.

Ngrok: https://ngrok.com/
Localtunnel: https://github.com/localtunnel/localtunnel

**Comment by agrinman** [comment]
Both are great projects, so kudos to them.
-Ngrok: our server is completely open source, reserving domains is much cheaper via https://dashboard.tunnelto.dev.
-Localtunnel: I don't believe you can reserve subdomains? This makes having persistent demos/tests/etc potentially impossible or at the very least, less secure.
